name: Show test results

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  old-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Show test results old
        uses: phoenix-actions/test-reporting@v15
        with:
          name: 'Dotnet tests report'
          path: ./TestResults/*.trx
          reporter: dotnet-trx
          output-to: 'step-summary'
  new-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Show test results old
        uses: OlesGalatsan/test-reporting@features/increase-summary-limit
        with:
          name: 'Dotnet tests report'
          path: ./TestResults/*.trx
          reporter: dotnet-trx
          output-to: 'step-summary'